"""initial schema

Revision ID: 25c572f029e1
Revises: 
Create Date: 2026-02-19 20:38:42.073066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c572f029e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horses')),
    sa.UniqueConstraint('name', 'sex', name='uq_horses_name_sex')
    )
    op.create_index(op.f('ix_horses_name'), 'horses', ['name'], unique=False)
    op.create_table('jockeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jockeys'))
    )
    op.create_index(op.f('ix_jockeys_name'), 'jockeys', ['name'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_model_versions_version'))
    )
    op.create_table('races',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.String(length=64), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('racecourse_code', sa.String(length=8), nullable=True),
    sa.Column('racecourse_name', sa.String(length=32), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('race_name', sa.String(length=128), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('weather', sa.String(length=16), nullable=True),
    sa.Column('track_condition', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_index('ix_races_date_course', 'races', ['race_date', 'racecourse_code'], unique=False)
    op.create_index(op.f('ix_races_race_date'), 'races', ['race_date'], unique=False)
    op.create_index(op.f('ix_races_race_id'), 'races', ['race_id'], unique=True)
    op.create_table('trainers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers'))
    )
    op.create_index(op.f('ix_trainers_name'), 'trainers', ['name'], unique=True)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('horse_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('predicted_position', sa.Integer(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_prediction_logs_horse_id_horses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_prediction_logs_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_prediction_logs_race_id_races'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_logs'))
    )
    op.create_table('race_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('horse_id', sa.Uuid(), nullable=False),
    sa.Column('jockey_id', sa.Uuid(), nullable=True),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('post_position', sa.Integer(), nullable=True),
    sa.Column('horse_age', sa.Integer(), nullable=True),
    sa.Column('carried_weight', sa.Float(), nullable=True),
    sa.Column('finishing_position', sa.Integer(), nullable=True),
    sa.Column('total_time_tenths', sa.Integer(), nullable=True),
    sa.Column('margin', sa.String(length=32), nullable=True),
    sa.Column('corner_pos_1', sa.Integer(), nullable=True),
    sa.Column('corner_pos_2', sa.Integer(), nullable=True),
    sa.Column('corner_pos_3', sa.Integer(), nullable=True),
    sa.Column('corner_pos_4', sa.Integer(), nullable=True),
    sa.Column('last_3f_time', sa.Float(), nullable=True),
    sa.Column('win_odds', sa.Float(), nullable=True),
    sa.Column('win_favorite', sa.Integer(), nullable=True),
    sa.Column('horse_weight', sa.Integer(), nullable=True),
    sa.Column('horse_weight_change', sa.Integer(), nullable=True),
    sa.Column('prize_money_10k_yen', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_race_entries_horse_id_horses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], name=op.f('fk_race_entries_jockey_id_jockeys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_entries_race_id_races'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_race_entries_trainer_id_trainers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_entries'))
    )
    op.create_index(op.f('ix_race_entries_finishing_position'), 'race_entries', ['finishing_position'], unique=False)
    op.create_index(op.f('ix_race_entries_horse_id'), 'race_entries', ['horse_id'], unique=False)
    op.create_index('ix_race_entries_race_horse', 'race_entries', ['race_id', 'horse_id'], unique=False)
    op.create_index(op.f('ix_race_entries_race_id'), 'race_entries', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_entries_race_id'), table_name='race_entries')
    op.drop_index('ix_race_entries_race_horse', table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_horse_id'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_finishing_position'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_trainers_name'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_races_race_id'), table_name='races')
    op.drop_index(op.f('ix_races_race_date'), table_name='races')
    op.drop_index('ix_races_date_course', table_name='races')
    op.drop_table('races')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_jockeys_name'), table_name='jockeys')
    op.drop_table('jockeys')
    op.drop_index(op.f('ix_horses_name'), table_name='horses')
    op.drop_table('horses')
    # ### end Alembic commands ###
