"""initial_schema

Revision ID: 84f2495ad016
Revises: 25c572f029e1
Create Date: 2026-02-19 20:40:37.552958
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "84f2495ad016"
down_revision: Union[str, None] = "25c572f029e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "race_entries", sa.Column("bracket_number", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "race_entries",
        sa.Column("weight_carried_kg", sa.Numeric(precision=4, scale=1), nullable=True),
    )
    op.add_column(
        "race_entries", sa.Column("finish_position", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "race_entries", sa.Column("finish_note", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "race_entries", sa.Column("horse_weight_kg", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "race_entries", sa.Column("horse_weight_diff", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "race_entries", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "race_entries",
        "post_position",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "horse_age",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "margin",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_1",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_2",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_3",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_4",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "last_3f_time",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=4, scale=1),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "win_odds",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=8, scale=1),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "win_favorite",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "prize_money_10k_yen",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=1),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_race_entries_finishing_position"), table_name="race_entries")
    op.drop_index(op.f("ix_race_entries_race_horse"), table_name="race_entries")
    op.create_index(
        op.f("ix_race_entries_finish_position"),
        "race_entries",
        ["finish_position"],
        unique=False,
    )
    op.create_index(
        "ix_race_entries_race_post",
        "race_entries",
        ["race_id", "post_position"],
        unique=True,
    )
    op.drop_column("race_entries", "horse_weight_change")
    op.drop_column("race_entries", "carried_weight")
    op.drop_column("race_entries", "horse_weight")
    op.drop_column("race_entries", "finishing_position")
    op.add_column(
        "races", sa.Column("graded_race", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "races",
        sa.Column(
            "race_symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "races",
        "race_number",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "races",
        "distance_m",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "races",
        "direction",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.drop_column("races", "grade")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "races",
        sa.Column("grade", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "races",
        "direction",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=8),
        existing_nullable=True,
    )
    op.alter_column(
        "races",
        "distance_m",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "races",
        "race_number",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("races", "race_symbols")
    op.drop_column("races", "graded_race")
    op.add_column(
        "race_entries",
        sa.Column(
            "finishing_position", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "race_entries",
        sa.Column("horse_weight", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "race_entries",
        sa.Column(
            "carried_weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "race_entries",
        sa.Column(
            "horse_weight_change", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index("ix_race_entries_race_post", table_name="race_entries")
    op.drop_index(op.f("ix_race_entries_finish_position"), table_name="race_entries")
    op.create_index(
        op.f("ix_race_entries_race_horse"),
        "race_entries",
        ["race_id", "horse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_race_entries_finishing_position"),
        "race_entries",
        ["finishing_position"],
        unique=False,
    )
    op.alter_column(
        "race_entries",
        "prize_money_10k_yen",
        existing_type=sa.Numeric(precision=10, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "win_favorite",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "win_odds",
        existing_type=sa.Numeric(precision=8, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "last_3f_time",
        existing_type=sa.Numeric(precision=4, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_4",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_3",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_2",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "corner_pos_1",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "margin",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "horse_age",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "race_entries",
        "post_position",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("race_entries", "owner")
    op.drop_column("race_entries", "horse_weight_diff")
    op.drop_column("race_entries", "horse_weight_kg")
    op.drop_column("race_entries", "finish_note")
    op.drop_column("race_entries", "finish_position")
    op.drop_column("race_entries", "weight_carried_kg")
    op.drop_column("race_entries", "bracket_number")
    # ### end Alembic commands ###
